### PR TITLE
Allow classic and modern engines to peacefully coexist

### PR DESCRIPTION
**Pull request by sbleon**
Fixes https://luceeserver.atlassian.net/browse/LDEV-2506

With this change, users can now specify which rendering engine to use on a per-document basis. This will make it much easier for users to migrate to the modern PDF engine.

I'm going to do a bit more testing on this, just to make sure all of the tag attributes still work.

### CODE REVIEW

**Comment by sbleon** [comment]
When merging this, we'll need to apply the commit https://github.com/singlebrook/extension-pdf/commit/2968553d889635421319243987fc6209a3281349 if #7 has been merged already.

**Comment by michaeloffner** [comment]
Thanks for your commit.
we need to take a very close look on this, in case evalAtPrint is set with documentIten the 
document tag is executed twice. It seems that point is not addressed at all. 
we do never use "_" for variable names, we use camel notation, in addition we try to avoid using prefixes whenever possible.
We have some System.out in the code that nbeed to be removed.

**Comment by michaeloffner** [comment]
we cannot do this
selectedType == 0
instead we need to do 
selectedType == PDF.TYPE_NONE;

everywhere where 0 is set, then change this
public static int PD4ML = 1;
public static int FS = 2;
to
public static int TYPE_NONE = 0;
public static int TYPE_PD4ML = 1;
public static int TYPE_FS = 2;

**Comment by michaeloffner** [comment]
i would also not use variables in Document for this, first the variables are set in a setter than again it is checked if they have been set and if so written to the PDFDocument.
This gives us unnecessary coordination of a lot of variables, better create a Setting object that you then pass to the PDFDocument, then the PDFDocument uses that object directly.

**Comment by sbleon** [comment]
Thanks for the feedback, @michaeloffner ! I've addressed the `_` in the variable names, and updated the `TYPE_*` variables.

I don't fully understand the `evalAtPrint` option. At first glance, it seems unrelated to the changes I've made here. How does it relate?

I agree that having a Settings object would be a cleaner design. Unfortunately, I don't think I'm going to have time to do that refactoring right now. Would you consider merging this without the refactoring if I added a TODO about it?

**Pull request merged**
