### PR TITLE
Added a additional info in fontdirectory - cfdocument for LDEV-2599 (ext-pdf)

### PR DESCRIPTION
**Pull request by cfmitrah**

### CODE REVIEW

**Comment by bdw429s** [comment]
@cfmitrah Isn't this worded backwards?  My understanding is that ONLY the old PDF engine supported the fontsdirectory and that the new PDF engine is the one that doesn't support it.  Can you confirm with Micha?

**Comment by andrew-dixon** [comment]
@cfmitrah There is also a typo, `addional` should be `additional`.

**Comment by zspitzer** [comment]
this should refer to the type="modern" attribute, not the name of underlying java library

https://github.com/lucee/extension-pdf/blob/master/source/tld/tag.tldx#L218

should also state, isn't currently supported for modern

https://github.com/lucee/lucee-docs/pull/1045

**Comment by cfmitrah** [comment]
I added a new PR with correction https://github.com/lucee/lucee-docs/pull/1230 . So I closed this.

**Pull request closed without merging**
