### PR TITLE
Added a fix to cfpdf action addHeader, addFooter throws NPE for LDEV-3587

### PR DESCRIPTION
**Pull request by cfmitrah**
https://luceeserver.atlassian.net/browse/LDEV-3587

### CODE REVIEW

**Comment by andyj** [comment]
Just wanted to confirm that I have compiled this pull request to test and deploy (until its merged) and it fixed my header/footer issues

**Comment by zspitzer** [comment]
can you add a test under `/tests/` ?

**Comment by cfmitrah** [comment]
@zspitzer Added testcase

**Comment by zspitzer** [comment]
think you need to rebase the PR

**Comment by cfmitrah** [comment]
I've created a new PR ( https://github.com/lucee/extension-pdf/pull/34 ) with the same changes. So I closed this.

**Pull request closed without merging**
